version: '2.2'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - mynetwork

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - '5173:5173'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
